/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gtfs.corev2;

import org.junit.Test;

import gtfs.corev2.nio.GTFSGraphBuilder;

import static org.junit.Assert.*;

import org.jgrapht.Graph;

public class GTFSnioTest {
    @Test 
    public void testLocalGraphBuilder() {
        Graph<GTFSVertex, GTFSEdge> g = 
        		new GTFSGraphBuilder("mbta")
        		.localDataset()
        		.build();
    }
}
